### ISSUE TITLE
Use as plugin with oh-my-zsh

### ISSUE THREAD

**Issue by thackl** [kloetzl/biozsh#4]
A really cool package! Just set it up, used @iimog's fix (https://github.com/kloetzl/biozsh/issues/2) to get the path right. And just in case it might be useful for others - my quick fix to install and load it as a oh-my-zsh plugin:

``` zsh
cd ~/.oh-my-zsh/custom/plugins/
git clone https://github.com/kloetzl/biozsh
cd biozsh
ln -s biozsh.sh biozsh.plugin.zsh # autoloads .plugin.zsh files
```
Add to `~/.zshrc` plugin list.
``` zsh
plugins=(git ... biozsh)
```

**Comment by kloetzl** [comment]
Is `biozsh.plugin.zsh` a file expected by oh-my-zsh? If so, feel free to create a pull request for your solution to help future users.

**Comment by thackl** [comment]
I think that your solution of pointing to the detailed install instructions in the Readme is absolutely sufficient.

**Comment by kloetzl** [comment]
Fine by me. 👍

**Comment by cgjosephlee** [comment]
A tidier one-liner for installation:
`git clone https://github.com/kloetzl/biozsh.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/biozsh`

**Comment by kloetzl** [comment]
Does that include the auto loading?

**Comment by cgjosephlee** [comment]
Nope, still requires `ln` step.

**Comment by kloetzl** [comment]
The symlink now comes with the repo as of PR #13.

**Comment by khughitt** [comment]
Out of curiosity, have you considered submitting this as an official plugin for oh-my-zsh? They have ~500 open PR's, so it may not be included anytime soon (assuming they decide to accept it), but seems like there are enough people who would find this useful to merit inclusion..

**Comment by kloetzl** [comment]
As I don't use oh-my-zsh I don't even know what “plugin” means in that context. Feel free to do whatever you seem fit to promote this project. :smiley:

**Comment by khughitt** [comment]
Ha, sounds good. I may take a stab at it if I find the time at some point. I'll keep you posted :)
